run: exit on fail
Signed-off-by: Filip Lobpreis <f.lobpreis@gmail.com>

diff --git a/run b/run
--- a/run
+++ b/run
@@ -10,9 +10,17 @@ esac
 
 if [[ $doc -eq 1 ]]; then
 	./compile --doc
+	ret=$?
 else
 	./compile
+	ret=$?
 fi
+
+if [[ $ret != 0 ]]; then
+	echo "Compilation failed"
+	exit $ret
+fi
+
 source ./install/setup.bash
 
 ros2 launch blackmetal blackmetal.launch.py
